elasticsearch_helper_content.index:
  type: sequence
  label: 'Entity type list'
  sequence:
    type: sequence
    label: 'Bundle list'
    sequence:
      type: elasticsearch_helper_content.bundle_normalizer.[%key]

elasticsearch_helper_content.bundle_normalizer.content:
  type: mapping
  label: 'Bundle configuration'
  mapping:
    normalizer:
      type: string
      label: 'Entity normalizer'

elasticsearch_helper_content.bundle_normalizer.field:
  type: mapping
  label: 'Bundle configuration'
  mapping:
    normalizer:
      type: string
      label: 'Entity normalizer'
    fields:
      type: sequence
      label: 'Fields to be displayed'
      mapping:
        normalizer:
          type: string
          label: 'Field normalizer'

views.filter.elasticsearch_index:
  type: views.filter.in_operator
